= Jeu _Rogue-Like_

.Complétez les informations ci-dessous.
[NOTE]
====
* Github URL : _GIT url_
* NOM 1 : _SMAHI, Abdeldjalil, 22205250_
* NOM 2 : _AMRANE, Younes, 21921438_
====

L'objet de ce mini-projet est de développer un jeu d'exploration de donjon de type https://fr.wikipedia.org/wiki/Rogue-like[Rogue-like].
Le thème que vous utiliserez pour ce projet est libre.
Vous devrez cependant respecter les contraintes fonctionnelles et techniques mentionnées ci-dessous.

[IMPORTANT]
====
Vous respecterez les contraintes suivantes:

* Ce mini-projet est à réaliser en Java par groupe de 2 étudiants.
** les 2 étudiants doivent collaborer sur le même dépôt github.
* Vous utiliserez `git` en effectuant des commits réguliers comportant des messages informatifs.
* Il devra comporter une documentation que vous ajouterez dans ce fichier `README.adoc`.
** la documentation devra décrire l'usage de l'application (_manuel utilisateur_) ainsi que la conception du jeu (_manuel technique_).
* Le _build_ sera assuré par Maven et plus précisément Maven wrapper (déjà intégré dans le projet).
Aucune manipulation en dehors de Maven ne devra être nécessaire.
* La version de Java à utiliser est la https://adoptium.net/[version 17].
* Le _build_ devra intégrer `checkstyle` pour la vérification des règles de codages Google.
Le projet devra donc les respecter.
`checkstyle` devra être exécuté automatiquement durant la phase `validate` du cycle de vie par défaut.
* Des tests unitaires https://junit.org/junit5/docs/current/user-guide/[JUnit 5] (version https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter/5.9.1[_5.9.1_]) devront être disponibles pour la plupart des méthodes développées.
* Un outil de https://fr.wikipedia.org/wiki/Couverture_de_code[_Code Coverage_] devra être intégré au _build_
* Les fonctionnalités du langage Java devront être utilisées au mieux (POO, exceptions, librairie de collections, I/O, …).
* L'application devra pouvoir être exécutée à partir d'un `jar` incluant toutes les dépendances.
====

== Description du jeu
* L'univers du jeu est représenté par un ensemble de cases carrées représentant différents éléments (_sol, mur, objet, personnage, …_).
* L'univers du jeu est généré aléatoirement en début de partie.
* Le jeu permet de déplacer un Personnage Joueur (PJ) en mode tour par tour.
* Le jeu comporte également des Personnages Non Joueur (PNJ).
* Le PJ possède des caractéristiques (_points de vie, de magie, …_) et un équipement (_pièces de monnaie, armes, …_).
* Le PJ peut interagir avec son environnement (_ramasser ou utiliser un objet, discuter avec un PNJ, combattre un monstre, …_).
* Les PNJ obéissent aux mêmes règles que le PJ mais sont contrôlés par le jeu.

== Description de l'application à réaliser
* L'interface proposera une visualisation de l'univers en mode texte (une case est représentée par un caractère symbole).
* Les actions du joueur seront saisies au clavier sous la forme `<action> <objet>` (par exemple `ramasser clé`).
* Une interface textuelle spécifique pourra être proposée pour des situations particulières (_création du personnage, sélection d'un sort, discussion, …_).
* L'état de la partie devra pouvoir être sauvegardée et rechargée à tout moment.

== Références
* Article Wikipedia https://fr.wikipedia.org/wiki/Rogue-like[Rogue-like]
* Tutoriels :
http://trystans.blogspot.fr/2016/01/roguelike-tutorial-00-table-of-contents.html[roguelike tutorial],
https://jellepelgrims.com/posts/roguelike_java[Writing a roguelike in Java]
* Quelques bibliothèques :
http://fusesource.github.io/jansi/[JAnsi] (couleur dans un terminal),
https://github.com/jline/jline3[JLine] (gestion des saisies)

== Manuel utilisateur
> À compléter :
> Le jeu Rogue Like se déroule dans un univers imaginaire, dans lequel le joueur incarne un personnage (PJ) à travers un monde rempli de monstres et de dangers.

> Le but du jeu est de parvenir à survivre le plus longtemps possible en évitant les attaques des monstres (PNJ) et en récoltant des armes et de l'équipement pour se défendre.

> Le PJ a des caractéristiques telles que sa santé, son équipement et ses compétences, qui peuvent être améliorées au fil de la partie.

> Les PNJ sont des monstres qui peuvent attaquer le PJ et le tuer s'il n'est pas suffisamment protégé ou s'il n'a pas assez de points de vie.

> Les interactions/commandes disponibles pour le joueur sont : déplacement du PJ, le ramassage d'armes et d'équipement à proximité, utilisation d'armes pour attaquer les monstres et le joueur peut à tout moment quitter la partie enregistrer son état.

> Il est possible d'envisager plusieurs évolutions pour le jeu, comme l'ajout de nouveaux niveaux, de nouvelles armes et de nouveaux monstres, ainsi que l'ajout de quêtes et de challenges à accomplir.

> Les commandes que l'utilisateur doit taper pour jouer :

*  z + Entrer pour aller en haut.
*  q + Entrer pour aller à gauche.
*  d + Entrer  pour aller à droite.
*	w + Entrer pour aller vers le bas.
*	e + Entrer pour prendre une arme.
*	exit +Entrer  pour quitter le jeu puis suivre des instructions.

> Les différentes représentations sur la carte:

* 	"@" représente le joueur.
*	"$"  représente le ou les dragons sur la map.
*	0 représente la sortie par laquelle il faut passer pour passer au niveau suivant.
*	# représente les obstacles soit des murs à l'intérieur de la map ou ses bordures.
*	? représente un Axe qui fait 10 de dommage.
*	! représente une Bat qui fait 5 de dommage.
*	P représente un Gun qui fait 15 de dommage.

== Manuel technique
=== Compiler le projet
.Sous Linux
----
$ ./mvnw package
----

.Sous Windows
----
> mvnw.cmd package
----

=== Éxécuter l'application
----
$ java -jar target/roguelike-1.0.jar
----

> À compléter :
> Comment consulter le rapport de couverture de code par les tests : mvn jacoco:test report puis en allant au dossier target/site/jacoco on trouve un fichier web index.html .

> Quelles bibliothèques ont été utilisées et pourquoi :

* JUnit 5.9.1 pour faire les tests unitaires .
* gson pour sérialiser l'objet Game afin d'enregistrer les parties sous format JSON.
* Jansi pour gérer les couleurs affichée sur la console .


> Quel est le rôle des différentes classes ?

* WorldComponentsType : un enum qui stocke les différents types de composants qui peuvent apparaître dans le monde du jeu (par exemple, murs, sol, sortie).
* WorldObject : une superclasse qui représente un objet générique dans le monde du jeu. Il a des attributs pour les coordonnées x et y de l'objet et le caractère ASCII, ainsi que des méthodes d'accès et de modification pour ces attributs.
* WorldComponent : une sous-classe de WorldObject qui représente un type spécifique de composant dans le monde du jeu (par exemple, mur, sol). Il a un attribut WorldComponentsType pour stocker le type de composant qu'il représente.
* TypeWeapon : un enum qui stocke les différents types d'armes qui peuvent apparaître dans le monde du jeu (par exemple, AXE, BAT, GUN).
* Weapon : une sous-classe de WorldObject qui représente une arme dans le monde du jeu. Il a un attribut TypeWeapon pour stocker le type d'arme qu'il représente, ainsi que des attributs pour les dégâts et la portée de l'arme.
* Personnage : une sous classe de WorldObject représente un OJ ou PNJ.
* Player : une classe qui représente le personnage du joueur. Il a des attributs pour la santé du joueur, son arme actuelle et sa position actuelle dans le monde du jeu, ainsi que des méthodes d'accès et de modification pour ces attributs. Il a également des méthodes pour se déplacer, ramasser des armes et attaquer des monstres.
* World : une classe qui représente le monde du jeu. Elle a un tableau 2D d'objets WorldObject pour stocker les objets dans le monde, ainsi que des méthodes pour ajouter et supprimer des objets du monde.
* Game : une classe qui regroupe tout et fait fonctionner le jeu. Elle utilise le modèle de commande pour gérer les actions du joueur et le modèle de constructeur pour construire le monde du jeu. Elle a également une méthode pour afficher le monde du jeu sur la console.
* Les classes command, qui gèrent le mouvement du joueur, le ramassage des armes,

> Quels traitements sont réalisés pour gérer une commande saisie par l'utilisateur ? Donnez un exemple.
    tout d'abord on vérifie si cette commande est valide, si c'est le cas ça dépend la valeur de son input, par exemple, si le joueur tape "z" c'est à dire qu'il veut faire un mouvement vers le haut, la commade Move s'execute en lui passant les attribut 1,0 et le world actuel, et le joueur. Une vérification des règles métiers du jeu se fait, on vérifie si le joueur peut bien bouger vers le haut s'il n'y a pas une arme ou un obstacle ou un monstre. Si c'est le cas on fait un swap entre le sol du haut et l'emplacement du joueur.

> Quelles améliorations peut-on envisager ?

Plusieurs améliorations peuvent etre envisagées, par exemple, on ajoutant quelques Armes, et que le joueur peut récolter de l'argent pour acheter une arme dès le démmarage du jeu, on ajoute un bouclier de Health pour qu'il puisse se soigner et en compliquant la diffuculté du jeu.
